# Generated by Django 5.1.14 on 2025-11-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banana', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='combo_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='daily_challenge_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='last_daily_challenge',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='max_combo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='perfect_solves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='puzzle_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='player',
            name='puzzles_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
